# Generated by Django 4.2.5 on 2023-09-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='layout',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
